### PR TITLE
move files under txs/ into txs package

### PR DESCRIPTION
**Pull request by silasdavis**
Minor clean-up exercise, but we would like to follow package naming conventions, particularly since it breaks some tooling to not.

### CODE REVIEW

**Comment by benjaminbollen** [comment]
Lets have full word naming conventions

**Comment by silasdavis** [comment]
@benjaminbollen what are you suggesting, to rename txs package to transactions?

**Comment by benjaminbollen** [comment]
yes, but we don't have to do this now; I mentioned it as a coding style Id prefer moving forward

**Comment by benjaminbollen** [comment]
fails on tests, but looks good to me

**Pull request merged**
