### PR TITLE
No global config (from tendermint)

### PR DESCRIPTION
**Pull request by ebuchman**
This should work after a glide install.

Install latest tendermint master.
Run `TMROOT=~/tmroot tendermint init`

and then `erisdb ~/tmroot inproc` should run erisdb inproc with tendermint over tmsp interface (you should see blocks)

Work on tests can resume in `rpc/tests`. eg. `go test --test.run Status` should pass, `go test --test.run Broadcast` should fail

### CODE REVIEW

**Comment by benjaminbollen** [comment]
"github.com/eris-ltd/eris-db/config" is still imported in 12 locations (2 in edbss)

**Comment by benjaminbollen** [comment]
Im also confused by the `TMROOT=~/tmroot tendermint init` instruction, what does `tendermint init` do?

**Comment by silasdavis** [comment]
@ebuchman by WIP, do you want to make some more changes before merging this, or would you like us to consider it now?

**Comment by benjaminbollen** [comment]
I changed the title to WIP as per comment above, there are still 10 locations where the deleted global config is used

**Comment by ebuchman** [comment]
hey ben, eris-db/config is out of scope for what I'm trying to achieve here. Note there's two configs, one for eris-db (using actual structs, defined in eris-db/config), and one from tendermint (using the tendermint/go-config abstraction).  this is merely about the latter. 

`tendermint init` is to drop a simple genesis.json so you can start the chain.

**Comment by benjaminbollen** [comment]
yes, I tried compiling this branch and that failed

**Comment by benjaminbollen** [comment]
apologies, must have made a merging error while testing, can't reproduce what I complained about above

**Comment by benjaminbollen** [comment]
https://github.com/eris-ltd/eris-db/pull/118/files#diff-d6abc2eecc18d84fbcfff38ac962d404R70

it can work if this is again moved to the separate file temporarily `server_config.toml`.  Currently it reads with above instructions the tendermint config.toml, then produces a runtime error when unmarshalling the toml config file into the ErisDBConfig struct, reading from it on L96.  Preferably we also panic on the error to read the config.

```
✔ ~/golang/src/github.com/eris-ltd/eris-db [test_no_global_config L|…3⚑ 6] 
18:25 $ ./prog ~/tmroot inproc
INFO[05-16|18:28:22] ErisDB Serve initializing.               module=eris/erisdb_server
EROR[05-16|18:28:22] Server config file error.                module=eris/erisdb_server error="toml: unmarshal: line 6: field corresponding to `node_laddr' is not defined in `*config.ErisDBConfig'"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x48acd2]

goroutine 1 [running]:
github.com/eris-ltd/eris-db/erisdb.ServeErisDB(0x7ffcb4739160, 0x14, 0xbe3701, 0x6, 0x0, 0x0)
	/home/bbollen/golang/src/github.com/eris-ltd/eris-db/erisdb/serve.go:96 +0x3c2
main.main()
	/home/bbollen/golang/src/github.com/eris-ltd/eris-db/cmd/erisdb/main.go:25 +0x13f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 20 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

**Comment by benjaminbollen** [comment]
when I locally fix the config files, it works for me and produces blocks !
@ebuchman can you review the above comment? thx
@silasdavis pinging you on this PR, for me this is good to go as a step forward.

**Comment by ebuchman** [comment]
oh ya - we should add to the defaults in config/config.go - mind making that change?

**Comment by silasdavis** [comment]
I'm not seeing the runtime error. I had to update glide deps to get log15 working though, so not sure if that has a bearing. I'm going to merge this even though I don't entirely understand Ben's remark, because I'm wild, and I want to PR some dependency clean-up on top of this.

**Comment by benjaminbollen** [comment]
The error should be reproducible if your `workdir` has a `config.toml` file but of the "united format", instead the current tendermint config file ; ie, hence my suggestion to have the edb config file under the different name, as is currently

**Pull request merged**
