### PR TITLE
Function signatures automated and fix set global

### PR DESCRIPTION
**Pull request by VoR0220**
Solves set_global portion and uint consistency on #417 . Also automates function identifier generation for a signature.

### CODE REVIEW

**Comment by silasdavis** [comment]
This looks good, but I'm thinking it would be nice to have a test closer to this file that would reassure as about changes. Can you link to an appropriate epm test?

**Comment by VoR0220** [comment]
@silasdavis certainly I can do that....once I make it. :P I'll make an update to the permissions test.

**Comment by benjaminbollen** [comment]
@silasdavis writing the unit tests for this was also still on my todo; happy for you to take this if you want.

**Comment by silasdavis** [comment]
Let's merge this for now. I've made an epic for further improvements: https://github.com/eris-ltd/eris-db/issues/496.

Unit tests are nice, but I think really its the cotnract-level/EPM tests that are going to give us most certainty.

@VoR0220 do I understand correctly that you plan to make a test for these in eris?

**Comment by VoR0220** [comment]
@silasdavis you are correct, I am working on one. But before that, I would like to know WHAT it is I am testing...because currently I have a vague idea of what setGlobal does.

**Comment by silasdavis** [comment]
Ah, so we do have some kind of tests for this here: https://github.com/eris-ltd/eris-db/blob/master/manager/eris-mint/state/permissions_test.go

I wonder why they didn't detect this change... will have to look into.

**Comment by VoR0220** [comment]
Because there wasnt a massive change...i just automated the func signatures. And we also dont test setGlobal currently.

**Comment by silasdavis** [comment]
No, actually we do test `set_global` here (in permission_test.go), that was the point of my link.

**Comment by VoR0220** [comment]
Ah crap missed that link...thought you were pointing at PM test. My bad.

**Comment by benjaminbollen** [comment]
To be clear: I asked for a unit test that had the hard-coded signatures in place; as a breaker for accidentally changing the signature, and as such the function identifier.

**Pull request merged**
